name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set variables for the run
        id: vars
        run: echo "::set-output name=version::${{ fromJson(./modinfo.json).version }}"
      - name: Bundle as zip
        run: zip -r recyclebackpacks.zip modinfo.json assets
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: steps.vars.outputs.version
          files: recyclebackpacks.zip
