name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set variables for the run
        id: vars
        run: |
          # https://stackoverflow.com/a/61919791
          modinfo=`cat ./modinfo.json`
          modinfo="${modinfo//'%'/'%25'}"
          modinfo="${modinfo//$'\n'/'%0A'}"
          modinfo="${modinfo//$'\r'/'%0D'}"
          echo "::set-output name=modinfo::$modinfo"
      - name: Create tag
        run: |
          git config --global user.name "GitHub Actions Agent"
          git config --global user.email "<>"
          if git show-ref --tags --verify --quiet "refs/tags/v${{ fromJson(steps.vars.outputs.modinfo).version }}"; then
            echo "Tag already exists"
            exit 1
          fi
          git tag -am "Create tag" "v${{ fromJson(steps.vars.outputs.modinfo).version }}"
          git push --no-verify --tags
          echo "Update the version number of the modinfo here"
          git commit -am "Bump version [skip ci]"
          git push --no-verify
