name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: "v${{ fromJson(steps.vars.outputs.modinfo).version }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set variables for the run
        run: |
          # https://stackoverflow.com/a/71758159
          modinfo=$(cat ./modinfo.json)
          echo "MODINFO<<EOF" >> $GITHUB_ENV
          cat ./modinfo.json >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Create tag
        run: |
          git config --global user.name "GitHub Actions Agent"
          git config --global user.email "<>"
          tagname="v${{ fromJson(env.MODINFO).version }}"
          git tag "$tagname"
          git push --no-verify --tags
          echo "tag=$tagname" >> $GITHUB_OUTPUT
      - name: Install tools
        uses: asdf-vm/actions/install@v4
      - name: Bump modinfo version
        run: node scripts/bump-version.js
      - name: Push version bump
        run: |
          git config --global user.name "GitHub Actions Agent"
          git config --global user.email "<>"
          git commit -am "Bump version [skip ci]"
          git push --no-verify
  release:
    uses: ./.github/workflows/release.yml
    needs: build
    with:
      tag: ${{ needs.build.outputs.tag }}
    permissions:
      contents: write
