name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: "v${{ steps.version-number.outputs.result }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Get version number
        id: version-number
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require("fs")
            const modinfo = JSON.parse(fs.readFileSync("./modinfo.json"))
            return modinfo.version
      - name: Create tag
        run: |
          git config --global user.name "GitHub Actions Agent"
          git config --global user.email "<>"
          tagname="v${{ steps.version-number.outputs.result }}"
          git tag "$tagname"
          git push --no-verify --tags
          echo "tag=$tagname" >> $GITHUB_OUTPUT
      - name: Install tools
        uses: asdf-vm/actions/install@v4
      - name: Bump modinfo version
        run: node scripts/bump-version.js
      - name: Push version bump
        run: |
          git config --global user.name "GitHub Actions Agent"
          git config --global user.email "<>"
          git commit -am "Bump version [skip ci]"
          git push --no-verify
  release:
    uses: ./.github/workflows/release.yml
    needs: build
    with:
      tag: ${{ needs.build.outputs.tag }}
    permissions:
      contents: write
