name: Release

on:
  workflow_call:
    inputs:
      tag:
        description: "What tag to make a release for"
        required: true
        type: string
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout tag
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: git checkout ${{ inputs.tag }}
      - name: Bundle as zip
        run: zip -r recyclebackpacks.zip modinfo.json assets
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          files: recyclebackpacks.zip
