name: Release

on:
  workflow_call:
    inputs:
      tag:
        description: "What tag to make a release for"
        required: true
        type: string
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get tag
        id: tag
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo "Workflow running against a tag: '${{ github.ref }}'"
            echo "::set-output name=tag::${{ github.ref }}
          else
            echo "Workflow not running against a tag: '${{github.ref}}', attempting to use input tag: '${{ input.tag }}'"
            echo "::set-output name=tag::${{ input.tag }}"
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: '${{ steps.tag.outputs.tag }}'
      - name: Bundle as zip
        run: zip -r recyclebackpacks.zip modinfo.json assets
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          files: recyclebackpacks.zip
