name: Release

on:
  workflow_call:
    inputs:
      tag:
        description: "What tag to make a release for"
        required: true
        type: string
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set variables
        id: vars
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            # https://unix.stackexchange.com/a/325492
            ref="${{ github.ref }}"
            version_tag=${ref##*/}
          else
            version_tag=${{ inputs.tag }}
          fi
          echo "tag=${version_tag}" >> $GITHUB_OUTPUT
          echo "zipfile=recyclebackpacks_${version_tag:1}.zip" >> $GITHUB_OUTPUT
      - name: Pretty version number
        id: version-number
        run: |
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: '${{ steps.vars.outputs.tag }}'
      - name: Bundle as zip
        run: zip -r ${{ steps.vars.outputs.zipfile }} modinfo.json assets
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          files: ${{ steps.vars.outputs.zipfile }}
